export const AUTH_USER = 'AUTH_USER';
export const AUTH_GOOGLE = 'AUTH_GOOGLE';
export const AUTH_FACEBOOK = 'AUTH_FACEBOOK';
export const AUTH_USER_START = 'AUTH_USER_START';
export const AUTH_USER_LOGOUT = 'AUTH_USER_LOGOUT';
export const AUTH_CHECK_LOGIN = 'AUTH_CHECK_LOGIN';

